title: Pyare Lal
#logo: /assets/img/headshot_circle.png
description: Ph.D. Scholar at Indian Institute of Science Education and Research, Bhopal (IISERB), India
#show_downloads: true
theme: jekyll-theme-minimal
